# JWT Configuration
jwt.secret=be36a0b2e9845e2787bdc1f1d725c551b93e18c8a75df9d61a14d6e3e2952b27f5b6fcf7107c587eaaaecd61872cc62581bcc51be0863d2dc4ff8fda85ce1da5f96b435a823e8770c6ce02264e0c64e53de08383bb518ff37f88611fa2b4a0cc69c50259acabfbf6396b05997841b11b85292cff3501b4f8466350dfe79598eacf3a4bfae18f2bb8ad6dec6030a961fdd2a3df672aeddb2a8e91e714e667e50a124b25a39cba43510154e5623a943c6d5681bef319f53df8bc9c2b9acc6eadbe631daa56916e86fb2fc81c5be7ced52dc0e3bdfa8a9b1a1c30dfee528fd9a755f08af454c56fa6ca16654b82ec6adb4822cdf60d35f287b442afcd6e106db1fb
jwt.expiration=900000
jwt.refresh-expiration=86400000 

# Security Configuration
app.password.reset.token.expiry=30
app.email.verification.expiry=1440 
app.max.failed.attempts=5
app.account.lock.time=1800000 
app.base.url=http://localhost:3000

# Email configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=shankarmerugu14@gmail.com
spring.mail.password=jcfrqciomshoboxj
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000

# CORS Configuration
security.allowed-origins=http://localhost:3000,http://localhost:3333

# Logging
logging.level.com.sas.Security=DEBUG
logging.level.org.springframework.security=INFO
logging.level.org.springframework.web=INFO
logging.file.name=logs/user-service.log
logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n